version: "3"

name: defects4j

services:
  frontend:
    image: defects4j
    build:
      context:  ./Defects4j-FlaskApp
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always

  nodejs:
    image: errorhandler
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
